/**
 * @ohos-tailscale/control 公开入口（barrel）。
 * 导出面 = docs/architecture.md §7 冻结契约 + 类型化消息层（RegisterRequest/
 * RegisterResponse/精简版 NetworkMap，任务书要求）；逐名显式导出。
 */

export { ControlError } from './errors.ts';

export {
  ControlTlvType,
  type ControlTlvTypeE,
  parseControlTlvType,
  ControlMsgKind,
  type ControlMsgKindE,
  parseControlMsgKind,
} from './types.ts';

export {
  controlTlvEncode,
  controlTlvDecode,
  controlEncodeMessage,
  controlDecodeMessage,
  type ControlTlvField,
  type ControlMessage,
} from './tlv.ts';

export {
  type RegisterRequest,
  registerRequestEncode,
  registerRequestDecode,
  registerRequestEncodeBytes,
  registerRequestDecodeBytes,
  type RegisterResponse,
  registerResponseEncode,
  registerResponseDecode,
  type NetworkMapPeer,
  type NetworkMap,
  networkMapEncode,
  networkMapDecode,
  networkMapDecodeBytes,
  encodeEndpointsValue,
  decodeEndpointsValue,
} from './messages.ts';

export { CONTROL_NOISE_PROLOGUE, ControlClient, type ControlClientConfig } from './client.ts';

export {
  TAILCFG_CURRENT_CAPABILITY_VERSION,
  formatNodeKey,
  encodeRegisterRequest,
  decodeRegisterResponse,
  encodeMapRequest,
  decodeMapResponseSummary,
  tailcfgError,
  type TailcfgRegisterRequest,
  type TailcfgRegisterAuth,
  type TailcfgHostinfo,
  type TailcfgRegisterResponse,
  type RegisterRequestParams,
  type TailcfgMapRequest,
  type MapRequestParams,
  type TailcfgMapResponseView,
} from './tailcfg.ts';

export {
  encodeMachineRequest,
  HttpOverNoiseReader,
  type HttpOverNoiseResponse,
} from './noisehttp.ts';

// ---- C1：netmap → WireGuard peer 配置推导（地址/前缀算术 + tailcfg 解码 + 推导） ----

export {
  addrEqual,
  addrToString,
  cgnatRange,
  chromeOsVmRange,
  comparePrefix,
  ipPortToString,
  isDerpMagicAddr,
  isDerpMagicAddrPort,
  isExitRoute,
  isLinkLocalUnicastAddr,
  isLoopbackAddr,
  isPrivateAddr,
  isTailscaleIp,
  maskedPrefix,
  parseIp,
  parseIpPort,
  parseIpv4,
  parseIpv6,
  parsePrefix,
  prefixContainsAddr,
  prefixContainsPrefix,
  prefixEqual,
  prefixHasHostBits,
  prefixIsSingleIp,
  prefixMaxBits,
  prefixToString,
  sortPrefixes,
  tailscaleUlaRange,
  tryParseIp,
  tryParseIpPort,
  unmapAddr,
  unmapPrefix,
  type IpAddr,
  type IpPort,
  type IpPrefix,
} from './netaddr.ts';

export {
  BAD_OLD_PREFIX_BYTES,
  DERP_CLEAN_STALE_INTERVAL_MS,
  DERP_INACTIVE_CLEANUP_MS,
  DERP_MAGIC_IP,
  DERP_WRITE_QUEUE_DEPTH,
  DISCO_PING_INTERVAL_MS,
  ENDPOINTS_FRESH_ENOUGH_MS,
  EXPIRY_RECHECK_SLACK_MS,
  FLAG_EXPIRED_PEERS_EPOCH_MS,
  GOOD_ENOUGH_LATENCY_MS,
  HEARTBEAT_INTERVAL_MS,
  INDEX_SENTINEL_DELETED,
  MIN_CLOCK_DELTA_MS,
  PING_TIMEOUT_MS,
  PONG_HISTORY_COUNT,
  SESSION_ACTIVE_TIMEOUT_MS,
  TRUST_UDP_ADDR_DURATION_MS,
  UPGRADE_UDP_DIRECT_INTERVAL_MS,
  WIREGUARD_ONLY_PROBE_MIN_INTERVAL_MS,
  WIREGUARD_ONLY_RECV_TRUST_MS,
  WIREGUARD_PING_INTERVAL_MS,
  CANDIDATE_PRUNE_THRESHOLD,
  DiscoPingPurpose,
  parseDiscoPingPurpose,
  SendRejection,
  type DiscoPingPurposeE,
  type SendRejectionE,
} from './smconsts.ts';

export {
  breakKeyWithBadOldPrefix,
  canonicalPeerId,
  capMapContains,
  ControlKnobs,
  decodeMapResponseFrame,
  decodePrefixList,
  mergeLegacyCapabilities,
  NodeAttrName,
  parseNodeAttrName,
  parseRfc3339Ms,
  upgradeNode,
  NetmapState,
  upgradedAllowedIpStrings,
  type MapResponseFrame,
  type MapResponseNode,
  type NetmapIngestOutcome,
  type NetmapPeerState,
  type NodeAttrNameE,
  type NodeCapMap,
  type PeerBoolChange,
  type PeerPatchFrame,
} from './netmap.ts';

export {
  deriveWgConfig,
  deriveWgPeer,
  diffWgPeers,
  type DeriveDiagnostics,
  type DerivePrefs,
  type WgDerivedConfig,
  type WgPeerDerived,
  type WgPeerDiff,
} from './wgderive.ts';

// ---- C2：peer 连接状态机（事件驱动、时钟注入、超时/心跳） ----

export {
  PeerEndpoint,
  type PeerEndpointDeps,
  type PeerNodeView,
  type PeerSink,
  type PeerStatusSnapshot,
  type PongReply,
  type SelfEndpointsView,
  type SendDecision,
  type TimeoutScheduler,
} from './peerconn.ts';

export {
  DerpRouteTable,
  type DerpCleanupResult,
  type DerpConnState,
  type DerpHomeChange,
  type DerpWriteRoute,
  type TimeoutSchedulerRef,
} from './derproute.ts';

// ---- C3：LocalAPI/IPC + PeerAPI + MagicDNS（协议语义纯逻辑层） ----

export {
  LOCAL_API_HOST,
  LOCAL_API_DEFAULT_SOCKET_PATH_LINUX,
  IPN_DEFAULT_CONTROL_URL,
  IpnState,
  ipnStateToString,
  parseIpnState,
  NotifyWatchOptBits,
  type NotifyWatchOptBitsE,
  parseNotifyWatchMask,
  validateNotifyWatchMask,
  LocalApiPermit,
  type LocalApiPermitE,
  type LocalApiRouteInfo,
  isKnownLocalApiRoute,
  localApiRoutePermit,
  type LocalApiTarget,
  parseLocalApiTarget,
  isSafeHttpMethod,
  localApiLogLine,
  type LocalApiGuardResult,
  checkLocalApiGuards,
  localApiValidHost,
  localApiBaseHeaders,
  parseUrlQuery,
  queryBool,
  buildLocalApiRequest,
  defaultIpnPrefs,
  cloneIpnPrefs,
  decodeMaskedPrefs,
  applyMaskedPrefs,
  type IpnPrefs,
  type IpnPrefsMask,
  type MaskedPrefsView,
  type IpnNotify,
  type NotifyNodeView,
  type StatusJsonView,
  type CurrentTailnetJsonView,
  type PeerStatusJsonView,
  type UserProfileJsonView,
  emptyIpnNotify,
  encodeIpnNotifyLine,
  decodeIpnNotifyLine,
  encodeNotifyStream,
  encodeStatusJson,
  dnsMessageTypeForString,
  type LocalStateEffect,
  localStateEffect,
} from './localapi.ts';

export {
  MAX_DNS_LABEL_LEN,
  MAX_DNS_NAME_LEN,
  MAGIC_DNS_POSITIVE_TTL_S,
  MAGIC_DNS_NEGATIVE_TTL_S,
  MAX_DNS_RESPONSE_BYTES,
  DNS_QUERY_TIMEOUT_MS,
  DNS_SYMBOLIC_FQDN,
  TAILSCALE_SERVICE_IP_V4,
  TAILSCALE_SERVICE_IP_V6,
  ULA_REVERSE_ZONE,
  DnsType,
  type DnsTypeE,
  DnsRCode,
  type DnsRCodeE,
  toFqdn,
  withTrailingDot,
  withoutTrailingDot,
  dnsNameHasSuffix,
  dnsNameContains,
  parentOf,
  magicDNSRootDomains,
  ipToPtrFqdn,
  ptrFqdnToIp,
  type DnsResolverSpec,
  type DnsRouteEntry,
  type DnsExtraRecord,
  type DnsNodeHostView,
  type NetmapDnsView,
  type DnsConfigForNetmap,
  type DnsHostEntry,
  rootDomainsOf,
  selfIsV6Only,
  extraRecordsToHosts,
  dnsConfigForNetmap,
  type MagicDnsResolverConfig,
  type MagicDnsOsConfig,
  type MagicDnsCompiled,
  compileMagicDnsConfig,
  type MagicDnsHostSource,
  type DnsAnswer,
  type DnsResolveOutcome,
  ResolverCore,
  shouldTruncate,
  magicDnsAddrs,
  canonicalNodeName,
} from './magicdns.ts';

export {
  PeerApiProto,
  type PeerApiProtoE,
  parsePeerApiProto,
  PEERAPI_FAKE_LISTENER_PORT,
  PEERAPI_PORT_TRIES,
  PEERAPI_HOST_LITERAL,
  crc32Ieee,
  derivePeerApiPort,
  type PeerApiListenerView,
  type TailcfgServiceView,
  peerApiServices,
  type PeerApiPorts,
  peerApiPortsOf,
  peerApiBase,
  type PeerApiRequestView,
  validatePeerApiRequest,
  peerCanProxyDNS,
  replyToDnsQueries,
  peerApiAddrIsValid,
} from './peerapi.ts';
